# Generated by Django 6.0.2 on 2026-02-06 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beneficiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("rg", models.CharField(max_length=20)),
                ("endereco", models.CharField(max_length=255)),
                ("recebe_beneficio", models.BooleanField(default=False)),
                (
                    "qual_beneficio",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "documento_foto",
                    models.ImageField(blank=True, null=True, upload_to="documentos/"),
                ),
                ("total_cestas_ano", models.PositiveIntegerField(default=0)),
                ("data_ultima_cesta", models.DateField(blank=True, null=True)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_concessao", models.DateField(auto_now_add=True)),
                (
                    "beneficiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cestas",
                        to="core.beneficiario",
                    ),
                ),
            ],
        ),
    ]
