# Generated by Django 6.0.2 on 2026-02-09 20:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beneficiario",
            name="data_ultima_cesta",
        ),
        migrations.RemoveField(
            model_name="beneficiario",
            name="total_cestas_ano",
        ),
        migrations.AlterField(
            model_name="beneficiario",
            name="documento_foto",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Documento"
            ),
        ),
    ]
