# Generated by Django 6.0.2 on 2026-02-09 22:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_beneficiario_data_cadastro_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cesta",
            name="data",
        ),
        migrations.AddField(
            model_name="beneficiario",
            name="data_cadastro",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cesta",
            name="data_concessao",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="beneficiario",
            name="documento_foto",
            field=models.ImageField(blank=True, null=True, upload_to="documentos/"),
        ),
        migrations.AlterField(
            model_name="beneficiario",
            name="endereco",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="beneficiario",
            name="nome",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="beneficiario",
            name="qual_beneficio",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
