# Generated by Django 6.0.2 on 2026-02-12 19:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_cesta_data_beneficiario_data_cadastro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiario",
            name="documento_foto",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="documento"
            ),
        ),
    ]
